controller_list:
  - name: fake_right_arm_controller
    joints:
      - link_1_joint
      - servo_2_joint
      - link_3_joint
      - link_4_joint
      - link_5_joint
  - name: fake_right_gripper_controller
    joints:
      []